kind: pipeline
type: docker
name: default

steps:
- name: build
  image: rust
  commands:
    - cargo build
    - cargo test

trigger:
  event:
    exclude:
    - tag

---
kind: pipeline
type: docker
name: release

steps:
- name: build
  image: clux/muslrust
  commands:
    - cargo build --release
    - mkdir coffer-${DRONE_TAG}-x86_64-musl
    - mv target/x86_64-unknown-linux-musl/release/coffer-server
         target/x86_64-unknown-linux-musl/release/coffer-client
         target/x86_64-unknown-linux-musl/release/coffer-companion
         coffer-${DRONE_TAG}-x86_64-musl
    - strip coffer-${DRONE_TAG}-x86_64-musl/coffer-server
    - strip coffer-${DRONE_TAG}-x86_64-musl/coffer-client
    - strip coffer-${DRONE_TAG}-x86_64-musl/coffer-companion

- name: package
  image: alpine
  commands:
    - tar cjf coffer-${DRONE_TAG}-x86_64-musl.tar.bz2
              coffer-${DRONE_TAG}-x86_64-musl/coffer-server
              coffer-${DRONE_TAG}-x86_64-musl/coffer-client
              coffer-${DRONE_TAG}-x86_64-musl/coffer-companion
    - tar czf coffer-${DRONE_TAG}-x86_64-musl.tar.gz
              coffer-${DRONE_TAG}-x86_64-musl/coffer-server
              coffer-${DRONE_TAG}-x86_64-musl/coffer-client
              coffer-${DRONE_TAG}-x86_64-musl/coffer-companion

- name: publish
  image: plugins/gitea-release
  settings:
    base_url: https://git.friedl.net
    api_key:
      from_secret: gitea_token
    files:
      - coffer-${DRONE_TAG}-x86_64-musl.tar.bz2
      - coffer-${DRONE_TAG}-x86_64-musl.tar.gz
    title: coffer ${DRONE_TAG}
    note: CHANGELOG.md
    checksum:
      - md5
      - sha256

trigger:
  event:
  - tag
